---
# Site
baseurl: "https://gov.ll.land"
title: "Liberland"
enableRobotsTXT: true
googleAnalytics: ""
# Content
languageCode: "en-us"
defaultContentLanguage: "en"
# Formats
metaDataFormat: "yaml"

menu:
  main:
  - identifier: news
    name: News
    url: /news/
    weight: 100

permalinks:
  news: /:year/:month/:title/

enableGitInfo: true

# -----------------------------
# DO NOT CHANGE BELOW THIS LINE
# -----------------------------
disableLiveReload: true
watch: false
---
