---
# Site
baseurl: "https://demo.liberland.org"
title: "Liberland"
enableRobotsTXT: true
googleAnalytics: ""
# Content
languageCode: "en-us"
defaultContentLanguage: "en"
# Formats
metaDataFormat: "yaml"

menu:
  main:
  - identifier: news
    name: News
    pre: <i class='fa fa-heart'></i>
    url: /news/
    weight: 100

permalinks:
  news: /:year/:month/:title/

# -----------------------------
# DO NOT CHANGE BELOW THIS LINE
# -----------------------------
disableLiveReload: true
watch: false
---
